title: n0signal
url: https://n0signal.dev
baseurl: ""
permalink: pretty

# projects 
collections:
  projects:
    output: true
    source: projects/_projects
    permalink: /projects/:slug/

defaults:
  - scope: { path: "", type: project }
    values: { layout: project }

  # posts
  - scope: { path: "blog/_posts", type: posts }
    values:
      layout: post
      permalink: /blog/:slug/
