title: n0signal
url: https://n0signal.dev
baseurl: ""
permalink: pretty

# projects 
collections_dir: projects

collections:
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
    
  # posts
  - scope:          
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:slug/
